Repository UofTGroup3/toronto-newcomers-guide, pull requests merged in 2023-08, with the labels that each got.

#12 # HTML Main Structure Implementation
  index.html
Labels: enhancement

#13 feature: added google translate
  assets/Script/app.js
  index.html
Labels: documentation

#16 # Updated Maps, added housing and settlement services
  assets/Script/app.js
  index.html
Labels: documentation, enhancement

#18 This adds recent local news articles for the city of Toronto
  assets/CSS/app.css
  assets/Script/app.js
  index.html
Labels: documentation, enhancement

#20 # This creates a dynamic dashboard page.
  assets/CSS/app.css
  assets/Script/app.js
  assets/images/ParallaxImages/Torornro.jpg
  assets/images/ParallaxImages/vladimir-visotsky-ZQKk3AXTGlQ-unsplash.jpg
  assets/images/TNG/400JpgdpiLogo.jpg
  assets/images/TNG/400JpgdpiLogoBW.jpg
  assets/images/TNG/400JpgdpiLogoCropped.jpg
  assets/images/TNG/400JpgdpiLogoCroppedBW.jpg
  assets/images/TNG/400PngdpiLogoBW.png
  assets/images/TNG/400PngdpiLogoCropped.png
  assets/images/TNG/400PngdpiLogoCroppedBW.png
  assets/images/TNG/953038438.pdf
  assets/images/TNG/EPSLogo.eps
  assets/images/TNG/FacebookCover.png
  assets/images/TNG/FacebookProfile.png
  assets/images/TNG/FaviconLogo.jpg
  assets/images/TNG/InstagramProfilePhoto.png
  assets/images/TNG/LinkedinCover.png
  assets/images/TNG/LinkedinProfile.png
  assets/images/TNG/MediumSquareLogo.jpg
  assets/images/TNG/MediumSquareLogoBWJpg.jpg
  assets/images/TNG/SVGLogo.svg
  assets/images/TNG/SmallSquareLogoBWJpg.jpg
  assets/images/TNG/SmallSquareLogoJpg.jpg
  assets/images/TNG/TwitterHeader.png
  assets/images/TNG/TwitterProfile.png
  assets/images/TNG/readme.txt
  dashboard.html
  index.html
Labels: enhancement

#21 # Final modification
  assets/CSS/app.css
  assets/Script/app.js
  dashboard.html
  index.html
Labels: documentation

#22 Updated news sources
  assets/Script/app.js
Labels: bug

#23 # This adds the README file
  README.md
  assets/CSS/app.css
  assets/images/TNG/demo.jpg
  index.html
Labels: documentation
